spring.application.name=DAWI_T2_FRANCO_LUIS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/bd_docentes
spring.datasource.username=root
spring.datasource.password=